import pandas as pd

TSv2_labels = {
    1: "spleen",
    2: "kidney_right",
    3: "kidney_left",
    4: "gallbladder",
    5: "liver",
    6: "stomach",
    7: "pancreas",
    8: "adrenal_gland_right",
    9: "adrenal_gland_left",
    10: "lung_upper_lobe_left",
    11: "lung_lower_lobe_left",
    12: "lung_upper_lobe_right",
    13: "lung_middle_lobe_right",
    14: "lung_lower_lobe_right",
    15: "esophagus",
    16: "trachea",
    17: "thyroid_gland",
    18: "small_bowel",
    19: "duodenum",
    20: "colon",
    21: "urinary_bladder",
    22: "prostate",
    23: "kidney_cyst_left",
    24: "kidney_cyst_right",
    25: "sacrum",
    26: "vertebrae_S1",
    27: "vertebrae_L5",
    28: "vertebrae_L4",
    29: "vertebrae_L3",
    30: "vertebrae_L2",
    31: "vertebrae_L1",
    32: "vertebrae_T12",
    33: "vertebrae_T11",
    34: "vertebrae_T10",
    35: "vertebrae_T9",
    36: "vertebrae_T8",
    37: "vertebrae_T7",
    38: "vertebrae_T6",
    39: "vertebrae_T5",
    40: "vertebrae_T4",
    41: "vertebrae_T3",
    42: "vertebrae_T2",
    43: "vertebrae_T1",
    44: "vertebrae_C7",
    45: "vertebrae_C6",
    46: "vertebrae_C5",
    47: "vertebrae_C4",
    48: "vertebrae_C3",
    49: "vertebrae_C2",
    50: "vertebrae_C1",
    51: "heart",
    52: "aorta",
    53: "pulmonary_vein",
    54: "brachiocephalic_trunk",
    55: "subclavian_artery_right",
    56: "subclavian_artery_left",
    57: "common_carotid_artery_right",
    58: "common_carotid_artery_left",
    59: "brachiocephalic_vein_left",
    60: "brachiocephalic_vein_right",
    61: "atrial_appendage_left",
    62: "superior_vena_cava",
    63: "inferior_vena_cava",
    64: "portal_vein_and_splenic_vein",
    65: "iliac_artery_left",
    66: "iliac_artery_right",
    67: "iliac_vena_left",
    68: "iliac_vena_right",
    69: "humerus_left",
    70: "humerus_right",
    71: "scapula_left",
    72: "scapula_right",
    73: "clavicula_left",
    74: "clavicula_right",
    75: "femur_left",
    76: "femur_right",
    77: "hip_left",
    78: "hip_right",
    79: "spinal_cord",
    80: "gluteus_maximus_left",
    81: "gluteus_maximus_right",
    82: "gluteus_medius_left",
    83: "gluteus_medius_right",
    84: "gluteus_minimus_left",
    85: "gluteus_minimus_right",
    86: "autochthon_left",
    87: "autochthon_right",
    88: "iliopsoas_left",
    89: "iliopsoas_right",
    90: "brain",
    91: "skull",
    92: "rib_left_1",
    93: "rib_left_2",
    94: "rib_left_3",
    95: "rib_left_4",
    96: "rib_left_5",
    97: "rib_left_6",
    98: "rib_left_7",
    99: "rib_left_8",
    100: "rib_left_9",
    101: "rib_left_10",
    102: "rib_left_11",
    103: "rib_left_12",
    104: "rib_right_1",
    105: "rib_right_2",
    106: "rib_right_3",
    107: "rib_right_4",
    108: "rib_right_5",
    109: "rib_right_6",
    110: "rib_right_7",
    111: "rib_right_8",
    112: "rib_right_9",
    113: "rib_right_10",
    114: "rib_right_11",
    115: "rib_right_12",
    116: "sternum",
    117: "costal_cartilages"
}

MAISI_labels = {
    "liver": 1,
    "dummy1": 2,
    "spleen": 3,
    "pancreas": 4,
    "right kidney": 5,
    "aorta": 6,
    "inferior vena cava": 7,
    "right adrenal gland": 8,
    "left adrenal gland": 9,
    "gallbladder": 10,
    "esophagus": 11,
    "stomach": 12,
    "duodenum": 13,
    "left kidney": 14,
    "bladder": 15,
    "dummy2": 16,
    "portal vein and splenic vein": 17,
    "dummy3": 18,
    "small bowel": 19,
    "dummy4": 20,
    "dummy5": 21,
    "brain": 22,
    "lung tumor": 23,
    "pancreatic tumor": 24,
    "hepatic vessel": 25,
    "hepatic tumor": 26,
    "colon cancer primaries": 27,
    "left lung upper lobe": 28,
    "left lung lower lobe": 29,
    "right lung upper lobe": 30,
    "right lung middle lobe": 31,
    "right lung lower lobe": 32,
    "vertebrae L5": 33,
    "vertebrae L4": 34,
    "vertebrae L3": 35,
    "vertebrae L2": 36,
    "vertebrae L1": 37,
    "vertebrae T12": 38,
    "vertebrae T11": 39,
    "vertebrae T10": 40,
    "vertebrae T9": 41,
    "vertebrae T8": 42,
    "vertebrae T7": 43,
    "vertebrae T6": 44,
    "vertebrae T5": 45,
    "vertebrae T4": 46,
    "vertebrae T3": 47,
    "vertebrae T2": 48,
    "vertebrae T1": 49,
    "vertebrae C7": 50,
    "vertebrae C6": 51,
    "vertebrae C5": 52,
    "vertebrae C4": 53,
    "vertebrae C3": 54,
    "vertebrae C2": 55,
    "vertebrae C1": 56,
    "trachea": 57,
    "left iliac artery": 58,
    "right iliac artery": 59,
    "left iliac vena": 60,
    "right iliac vena": 61,
    "colon": 62,
    "left rib 1": 63,
    "left rib 2": 64,
    "left rib 3": 65,
    "left rib 4": 66,
    "left rib 5": 67,
    "left rib 6": 68,
    "left rib 7": 69,
    "left rib 8": 70,
    "left rib 9": 71,
    "left rib 10": 72,
    "left rib 11": 73,
    "left rib 12": 74,
    "right rib 1": 75,
    "right rib 2": 76,
    "right rib 3": 77,
    "right rib 4": 78,
    "right rib 5": 79,
    "right rib 6": 80,
    "right rib 7": 81,
    "right rib 8": 82,
    "right rib 9": 83,
    "right rib 10": 84,
    "right rib 11": 85,
    "right rib 12": 86,
    "left humerus": 87,
    "right humerus": 88,
    "left scapula": 89,
    "right scapula": 90,
    "left clavicula": 91,
    "right clavicula": 92,
    "left femur": 93,
    "right femur": 94,
    "left hip": 95,
    "right hip": 96,
    "sacrum": 97,
    "left gluteus maximus": 98,
    "right gluteus maximus": 99,
    "left gluteus medius": 100,
    "right gluteus medius": 101,
    "left gluteus minimus": 102,
    "right gluteus minimus": 103,
    "left autochthon": 104,
    "right autochthon": 105,
    "left iliopsoas": 106,
    "right iliopsoas": 107,
    "left atrial appendage": 108,
    "brachiocephalic trunk": 109,
    "left brachiocephalic vein": 110,
    "right brachiocephalic vein": 111,
    "left common carotid artery": 112,
    "right common carotid artery": 113,
    "costal cartilages": 114,
    "heart": 115,
    "left kidney cyst": 116,
    "right kidney cyst": 117,
    "prostate": 118,
    "pulmonary vein": 119,
    "skull": 120,
    "spinal cord": 121,
    "sternum": 122,
    "left subclavian artery": 123,
    "right subclavian artery": 124,
    "superior vena cava": 125,
    "thyroid gland": 126,
    "vertebrae S1": 127,
    "bone lesion": 128,
    "dummy6": 129,
    "dummy7": 130,
    "dummy8": 131,
    "airway": 132
}


def create_mapping_excel_files(tsv2_labels, maisi_labels):
    # Create matched labels dataframe
    matched_data = []
    for tsv2_idx, tsv2_name in tsv2_labels.items():
        # Convert naming convention
        converted_name = tsv2_name.replace('_', ' ')
        for maisi_name, maisi_idx in maisi_labels.items():
            if converted_name.replace('left ', '').replace('right ', '') == maisi_name.replace('left ', '').replace('right ', ''):
                matched_data.append({
                    'Organ/Structure': tsv2_name,
                    'TSv2 Index': tsv2_idx,
                    'MAISI Index': maisi_idx,
                    'TSv2 Label': tsv2_name,
                    'MAISI Label': maisi_name
                })
                break
    
    matched_df = pd.DataFrame(matched_data)
    
    # Create unmatched labels dataframe
    maisi_indices = set(maisi_labels.keys())
    matched_maisi = set(row['MAISI Label'] for row in matched_data)
    unmatched_maisi = maisi_indices - matched_maisi
    
    unmatched_data = [
        {
            'Label': label,
            'MAISI Index': maisi_labels[label],
            'Notes': 'Only in MAISI'
        }
        for label in unmatched_maisi
    ]
    
    unmatched_df = pd.DataFrame(unmatched_data)
    
    # Create converted dictionaries dataframe
    converted_data = []
    for tsv2_idx, tsv2_name in tsv2_labels.items():
        converted_name = tsv2_name.replace('_', ' ')
        for maisi_name, maisi_idx in maisi_labels.items():
            if converted_name.replace('left ', '').replace('right ', '') == maisi_name.replace('left ', '').replace('right ', ''):
                converted_data.append({
                    'Original TSv2 Index': tsv2_idx,
                    'Original TSv2 Label': tsv2_name,
                    'Converted MAISI Index': maisi_idx,
                    'Converted MAISI Label': maisi_name
                })
                break
    
    converted_df = pd.DataFrame(converted_data)
    
    # Save to Excel files
    with pd.ExcelWriter('label_mappings.xlsx') as writer:
        matched_df.to_excel(writer, sheet_name='Matched Labels', index=False)
        unmatched_df.to_excel(writer, sheet_name='Unmatched Labels', index=False)
        converted_df.to_excel(writer, sheet_name='Converted Labels', index=False)

# Generate the Excel files
create_mapping_excel_files(TSv2_labels, MAISI_labels)